etv/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

from django.urls import path, include
from django.views.generic import RedirectView
from accounts.admin import admin_site

from .views import *
from accounts.views import LoginView, RegisterView, GuestRegisterView
from content.views import efbf, contact, mailchimp_signup

from policy.views import obb_flyer
from vbp.models import *
from ven.views import *

from merchandise.views import ProductList

Alabama = vbp_al.objects.filter(approved=False).count()
Alaska = vbp_ak.objects.filter(approved=False).count()
Arizona = vbp_az.objects.filter(approved=False).count()
Arkansas = vbp_ar.objects.filter(approved=False).count()
California = vbp_ca.objects.filter(approved=False).count()
Colorado = vbp_co.objects.filter(approved=False).count()
Connecticut = vbp_ct.objects.filter(approved=False).count()
Delaware = vbp_de.objects.filter(approved=False).count()
DistrictofColumbia = vbp_dc.objects.filter(approved=False).count()
Florida = vbp_fl.objects.filter(approved=False).count()
Georgia = vbp_ga.objects.filter(approved=False).count()
Hawaii = vbp_hi.objects.filter(approved=False).count()
Idaho = vbp_id.objects.filter(approved=False).count()
Illinois = vbp_il.objects.filter(approved=False).count()
Indiana = vbp_in.objects.filter(approved=False).count()
Iowa = vbp_ia.objects.filter(approved=False).count()
Kansas = vbp_ks.objects.filter(approved=False).count()
Kentucky = vbp_ky.objects.filter(approved=False).count()
Louisiana = vbp_la.objects.filter(approved=False).count()
Maine = vbp_me.objects.filter(approved=False).count()
Maryland = vbp_md.objects.filter(approved=False).count()
Massachusetts = vbp_ma.objects.filter(approved=False).count()
Michigan = vbp_mi.objects.filter(approved=False).count()
Minnesota = vbp_mn.objects.filter(approved=False).count()
Mississippi = vbp_ms.objects.filter(approved=False).count()
Missouri = vbp_mo.objects.filter(approved=False).count()
Montana = vbp_mt.objects.filter(approved=False).count()
Nebraska = vbp_ne.objects.filter(approved=False).count()
Nevada = vbp_nv.objects.filter(approved=False).count()
NewHampshire = vbp_nh.objects.filter(approved=False).count()
NewJersey = vbp_nj.objects.filter(approved=False).count()
NewMexico = vbp_nm.objects.filter(approved=False).count()
NewYork = vbp_ny.objects.filter(approved=False).count()
NorthCarolina = vbp_nc.objects.filter(approved=False).count()
NorthDakota = vbp_nd.objects.filter(approved=False).count()
Ohio = vbp_oh.objects.filter(approved=False).count()
Oklahoma = vbp_ok.objects.filter(approved=False).count()
Oregon = vbp_or.objects.filter(approved=False).count()
Pennsylvania = vbp_pa.objects.filter(approved=False).count()
RhodeIsland = vbp_ri.objects.filter(approved=False).count()
SouthCarolina = vbp_sc.objects.filter(approved=False).count()
SouthDakota = vbp_sd.objects.filter(approved=False).count()
Tennessee = vbp_tn.objects.filter(approved=False).count()
Texas = vbp_tx.objects.filter(approved=False).count()
Utah = vbp_ut.objects.filter(approved=False).count()
Vermont = vbp_vt.objects.filter(approved=False).count()
Virginia = vbp_va.objects.filter(approved=False).count()
Washington = vbp_wa.objects.filter(approved=False).count()
WestVirginia = vbp_wv.objects.filter(approved=False).count()
Wisconsin = vbp_wi.objects.filter(approved=False).count()
Wyoming = vbp_wy.objects.filter(approved=False).count()

urlpatterns = [
    path('contact/', contact, name='contact' ),
    path('myadmin/etvadmin209423/', admin_site.urls, {'extra_context': {
        'AL': Alabama,
        'AK': Alaska,
        'AZ': Arizona,
        'AR': Arkansas,
        'CA': California,
        'CO': Colorado,
        'CT': Connecticut,
        'DE': Delaware,
        'DC': DistrictofColumbia,
        'FL': Florida,
        'GA': Georgia,
        'HI': Hawaii,
        'ID': Idaho,
        'IL': Illinois,
        'IN': Indiana,
        'IA': Iowa,
        'KS': Kansas,
        'KY': Kentucky,
        'LA': Louisiana,
        'ME': Maine,
        'MD': Maryland,
        'MA': Massachusetts,
        'MI': Michigan,
        'MN': Minnesota,
        'MS': Mississippi,
        'MO': Missouri,
        'MT': Montana,
        'NE': Nebraska,
        'NV': Nevada,
        'NH': NewHampshire,
        'NJ': NewJersey,
        'NM': NewMexico,
        'NY': NewYork,
        'NC': NorthCarolina,
        'ND': NorthDakota,
        'OH': Ohio,
        'OK': Oklahoma,
        'OR': Oregon,
        'PA': Pennsylvania,
        'RI': RhodeIsland,
        'SC': SouthCarolina,
        'SD': SouthDakota,
        'TN': Tennessee,
        'TX': Texas,
        'UT': Utah,
        'VT': Vermont,
        'VA': Virginia,
        'WA': Washington,
        'WV': WestVirginia,
        'WI': Wisconsin,
        'WY': Wyoming,
    }}, name='myadmin', ),
    path('', home_page, name='home'),
    path('privacy-policy', privacy, name="privacy"),
    path('terms-and-conditions', terms, name="terms"),
    path('about/', about_page, name='about'),
    path('accounts/', RedirectView.as_view(url='/account')),
    path('account/', include(("accounts.urls", "accounts"), namespace='account')),
    path('black-friday-challenge/', include(("bfchallenge.urls", "bfchallenge"), namespace='bfchallenge')),
    path('billing/', include(("billing.urls", "billing"), namespace='billing')),
    path('cart/', include(("carts.urls", "carts"), namespace='carts')),
    path('dashboard/', include(("dashboard.urls", "dashboard"), namespace='dashboard')),
    path('donation/', include(("donations.urls", "donations"), namespace='donation')),
    path('economic-prosperity-and-employment/', include(("prosperity.urls", "prosperity"), namespace='prosperity')),
    path('events/', include(("events.urls", "events"), namespace='events')),
    path('news/', news, name='news'),
    path('news-and-events/', news, name='news'),
    path('sitemap.xml/', sitemap),
    path('robots.txt/', robots),
    path('shop/', ProductList, name='shop'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page=settings.LOUGOUT_REDIRECT_URL), name='logout'),
    path('make-every-friday-black-friday/', efbf, name='efbf'),
    path('mailchimp-signup/', mailchimp_signup, name='mailchimp-signup'),
    path('merchandise/', include(("merchandise.urls", "merchandise"), namespace='merchandise')),
    path('obb-<state>/', obb_flyer),
    path('register/', RegisterView.as_view(), name='register'),
    path('register/guest', GuestRegisterView.as_view(), name='guest_register'),
    path('scraper/', include(("scraper.urls", "scaper"), namespace="scraper")),
    path('settings/', RedirectView.as_view(url='/account')),
    path('strategic-pillars/', strategic_pillars, name='pillars'),
    path('village-black-pages/', include(("vbp.urls", "vbp"), namespace='vbp')),
    path('', include('social_django.urls', namespace='social')),
    path('health-and-wellness/', include(("health.urls", "health"), namespace='health')),
    path('policy-and-power/', include(("policy.urls", "policy"), namespace='policy')),
    path('education/', include(("education.urls", "education"), namespace='education')),
    path('walkathon/', include(("walkathon.urls", "walkathon"), namespace="walkathon")),
    path('power-walk-2023/', include(("walkathon.urls", "walkathon"), namespace="power-walk")),
    path('power-walk-2024/', include(("walkathon.urls", "walkathon"), namespace="power-walk-24")),
    path('village-empowerment-network/', include(("ven.urls", "ven"), namespace='ven')),
    path('village-empowerment-network-nomination/', venForm, name='ven-nomination'),
    path('tinymce/', include('tinymce.urls')),
    
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

merchandise/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', ProductList, name='list'),
    path('add-to-cart', AddToCart, name='add-to-cart'),
    path('remove-from-cart', RemoveFromCart, name='remove-from-cart')
]

merchandise/models.py
import random
from django.db import models
from django.db.models import Q
from django.http import HttpResponse
from django.urls import reverse
from etv.utils import *
from django.db.models.signals import pre_save, post_save

class VariationManager(models.Manager):
    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id)
        if qs.count() == 1:
            return qs.first()
        return None
    
class size(models.Model):
    size        = models.CharField(max_length=270)
    order       = models.IntegerField(null=True, blank=True)

    objects     = VariationManager()
    def __str__(self):
        return self.size

    class Meta:
        ordering = ['order',]

class color(models.Model):
    color   = models.CharField(max_length=270)

    def __str__(self):
        return self.color


class image(models.Model):
    image   = models.FileField()
    image_id      = models.CharField(max_length=50, null=True, blank=True, unique=True)
    default = models.BooleanField(default=False)
    order_by    = models.IntegerField(blank=True, null=True)

    class Meta:
        verbose_name = "Image"
        verbose_name_plural = "Images"
        ordering = ['order_by',]

    def __str__(self):
        return str(self.image)

    def get_path(self):
        return 'https://d1z669787inm16.cloudfront.net/media/%s' %(self.image)

def pre_save_create_image_id(sender, instance, *args, **kwargs):
    if not instance.image_id:
        instance.image_id = unique_image_id_generator(instance)

pre_save.connect(pre_save_create_image_id, sender=image)

class CloudflareImage(models.Model):
    image_url               = models.CharField(max_length=320)
    
    def __str__(self):
        return str(self.image_url)

class Variation(models.Model):
    size = models.ForeignKey(size, on_delete=models.CASCADE, null=True, blank=True)
    color = models.ForeignKey(color, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return '%s-%s' %(self.size, self.color)

class newProduct(models.Model):
    title       = models.CharField(max_length=250)
    slug        = models.SlugField(blank=True, unique=True)
    description = models.TextField(blank=True, null=True)
    card_description = models.TextField(blank=True, null=True)
    price       = models.DecimalField(decimal_places=2, max_digits=10, default=0.00)
    featured    = models.BooleanField(default=False)
    active      = models.BooleanField(default=True)
    shipping_weight = models.IntegerField(null=True, blank=True)
    sale_active = models.BooleanField(default=False)
    sale_price  = models.DecimalField(decimal_places=2, max_digits=10, default=0.00, blank=True)
    images = models.ManyToManyField(CloudflareImage, blank=True)
    inventory   = models.ManyToManyField(Variation, through='newInventory')
    display_order       = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['display_order', 'price']
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    @property
    def get_images(self):
        return self.images.all()

    @property
    def get_colors(self):
        colors = set(self.inventory.select_related('color').distinct("color").all()) 
        return colors

    @property
    def get_sizes(self):
        sizes = self.inventory.distinct('size').all()
        return sizes

def newproduct_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(newproduct_pre_save_receiver, sender=newProduct)

def inventory_sku_generator(instance, new_sku=None):
    """
    This is for a Django project and it assumes your instance
    has a model with a slug field and a title character (char) field.
    """
    if new_sku is not None:
        sku = new_sku
    else:
        sku = "{id}-{randstr}".format(
                    id=instance.product.id,
                    randstr=random_string_generator(size=4)
                )

    Klass = instance.__class__
    qs_exists = Klass.objects.filter(sku=sku).exists()
    if qs_exists:
        new_sku = "{id}-{randstr}".format(
                    sku=sku,
                    randstr=random_string_generator(size=4)
                )
        return inventory_sku_generator(instance, new_sku=new_sku)
    return sku

class newInventory(models.Model):
    sku         = models.CharField(max_length=270, blank=True, null=True)
    product     = models.ForeignKey(newProduct, on_delete=models.CASCADE)
    variation   = models.ForeignKey(Variation, on_delete=models.CASCADE)
    quantity    = models.IntegerField(default=1)

    def __str__(self):
        return self.sku

    class Meta:
        ordering = ['sku', 'quantity']
        verbose_name = 'SKU'
        verbose_name_plural = 'Inventory'

def inventory_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.sku:
        instance.sku = inventory_sku_generator(instance)

pre_save.connect(inventory_pre_save_receiver, sender=newInventory)

merchandise/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import *
from django.http import Http404, JsonResponse
from carts.models import Cart, cartItem
from django.db.models import Q

import django_filters
import sweetify

def ProductList(request):
    object_list = newProduct.objects.all()
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    cart_items = cartItem.objects.filter(cart=cart_obj)
    context = {
        'cart': cart_obj,
        'cart_items': cart_items,
        'title': 'ETV | Shop',
        'object_list': object_list
    }
    return render(request, 'new_list.html', context)

def AddToCart(request):
    color = request.GET['color']
    id = request.GET['id']
    size = request.GET['size']
    order_sku = '%s-%s-%s' %(id, size, color)
    inv_item = newInventory.objects.filter(sku=order_sku).first()
    (invItem) = inv_item
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    cart_item = cartItem.objects.filter(item=invItem, cart=cart_obj).first()
    if cart_item is not None:
        cart_item.quantity += 1
        print(cart_item.quantity)
        cart_item.save()
    else:
        obj = cartItem()
        obj.cart = cart_obj
        obj.item = invItem
        obj.quantity = 1
        obj.product = invItem.product
        obj.save()
    
    return redirect('merchandise:list')

def RemoveFromCart(request):
    color = request.GET['color']
    id = request.GET['id']
    size = request.GET['size']
    order_sku = '%s-%s-%s' %(id, size, color)

    if order_sku is not None:
        inventoryItem = newInventory.objects.filter(sku=order_sku).first()
        (invItem) = inventoryItem
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        (cart_items) = cart_obj.items.filter(sku=invItem).first()
        if cart_items is not None:
            item_obj = cart_items
            currentQuantity = item_obj.quantity
            item_obj.quantity = currentQuantity - 1
            item_obj.save()
        else:
            errorData = str('Nothing to remove!')
                
    return redirect('merchandise:list')

def cart_update(request):
    type = request.POST.get('type')
    size = request.POST.get('size')
    color = request.POST.get('color')
    if type is not None:
        
        try:
            item_obj = newInventory.objects.get(type=type, color=color, size=size)
        except:
            added = False
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if item_obj in cart_obj.products.all():
            cart_obj.products.remove(item_obj)
            added = False
        else:
            cart_obj.products.add(item_obj)
            added = True
        request.session['cart_items'] = cart_obj.products.count()
        if request.is_ajax():
            json_data = {
                "added": added,
                "removed": not added,
                "cartItemCount": cart_obj.products.count(),
            }
            return JsonResponse(json_data)
    return redirect('merchandise:list')

merchandise/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ object.title }} | The Commerce Code{% endblock %}

{% block content %}
<div class="container" style="padding-top: 40px; padding-bottom: 40px">
    <div class=row>
        <div class="col-sm-12 col-md-10">
            <h5 class="detail-title">{{ object.title }}</h5>
            <div class="">
                {% if object.thumbnail %}
                <img src="{{ object.thumbnail }}">
                {% endif %}
                <video style="margin: 30px 0px" class="shadow-2-strong" controls=True width=100% src="https://file-examples-com.github.io/uploads/2017/04/file_example_MP4_480_1_5MG.mp4"></video>
            </div>
            {% if object.free == True %}
            <h7 class="list-group-free">FREE</h7>
            {% else %}
            <h7 class="list-group-price">${{ object.price }}</h7>
            {% endif %}
            <p class="list-group-description">{{ object.description }}</p>

            <div class="row">
                {% for skill in object.skills.all %}
                <div class="chip">
                    <img src="{% static 'img/html.png' %}" width="96" height="96">
                    {{ skill }}
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-sm-12 col-md-2">
            <div class="accordion accordion-flush" id="accordionFlushExample">
                {% for lesson in object.lessons.all %}
                <div class="accordion-item">
                  <h2 class="accordion-header" id="flush-heading{{ lesson.number }}">
                    <button
                      class="accordion-button collapsed"
                      type="button"
                      data-mdb-toggle="collapse"
                      data-mdb-target="#flush-collapse{{ lesson.number }}"
                      aria-expanded="false"
                      aria-controls="flush-collapse{{ lesson.number }}"
                    >
                      {{ lesson.title }}
                    </button>
                  </h2>
                  <div
                    id="flush-collapse{{ lesson.number }}"
                    class="accordion-collapse collapse"
                    aria-labelledby="flush-heading{{ lesson.number }}"
                    data-mdb-parent="#accordionFlushExample"
                  >
                    <div class="accordion-body">
                      {{ lesson.number }}
                    </div>
                  </div>
                </div>
                {% endfor %}
              </div>
        </div>
    </div>
    

    
</div>
{% endblock %}

merchandise/templates/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}

{% block content %}

<div class="" style="background: url('{% static 'img/pillar_collage.png' %}');">
    <div id="merchandise-container">
            <div class="row" style="margin-bottom: 0">
                <h5 class="page-title">SHOW YOUR SUPPORT</h5>
                        <h6 class="donation-subtitle"><b>EMPOWER THE VILLAGE  MERCHANDISE</b> helps support the work we do to bring prosperity, peace and power back to our community</h6>
            </div>
            <div class="row merch-row1" style="margin-bottom: 0">
                
                {% for obj in object_list %}

                    <div class="col s12 m6 l4 card-column">
                        <div class="card">
                            <div class="card-image z-depth-1">
                                <div class="carousel carousel-slider" id="product-carousel">
                                    {% for image in obj.get_images %}
                                    <div class="carousel-item">
                                            <a class="" style="display: flex" data-lightbox="{{ obj.slug }}" href="{{ image.get_path }}"><img class="carousel-image-item" src="{{ image.get_path }}"></a>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="card-content center-align">
                                <div class="card-title">{{ obj.title }}</div>
                                <p class="card-price">${{ obj.price }}</p>
                                <div class="card-info">
                                
                                <p>{{ obj.card_description}}</p>
                                <form class="ajax-product-form">
                                    <input class="product-id-hidden" type="hidden" value="{{ obj.id }}">
                                    <div class="row valign-wrapper" style="margin-bottom: 0; display: flex; justify-content: center;">
                                        

                                    {% for color in obj.get_colors %}
                                            <div class="col" style="padding:5px; margin:0">
                                                <label>
                                                    <input class="select-color" value="{{ color }}" name="{{ obj.slug }}-color" type="radio">
                                                    <span class="color-radio" id="{{ obj.slug }}-{{ color }}"></span>
                                                </label>
                                                <p class="color-label" style="margin-top: 10px" >{{ color }}</p>
                                            </div>
                                            <style>
                                                #{{obj.slug}}-{{ color }}::before {
                                                    background: {{ color }}
                                                }
                                            </style>
                                    {% endfor %}
                                    </div>
                                    {% if obj.get_sizes|length > 1 %}
                                    <div class="row size-row">
                                        <div class="input-field size-field" style="z-index:500">
                                            <select class="size-select">
                                                <option value="" selected style="color: grey">Choose Size</option>
                                                {% for size in obj.get_sizes %}
                                                    <option value="{{ size }}" style="z-index:500">{{ size }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                    </div>
                                    {% else %}
                                    <div class="size-select" style="display:none">
                                        {% for size in obj.get_sizes %}
                                        <option selected value="{{ size }}"></option>
                                        {% endfor %}
                                    </div>
                                    {% endif %}
                                    <div class="row" style="margin:0">
                                        
                                            <span class="submit-span">
                                            <button class="btn" type="submit">Add To Cart</button>
                                            </span>
                                        
                                    </div>
                                </form>
                            </div>
                            </div>
                        </div>
                    </div>
                    
                {% endfor %}
            </div>
    </div>
    
</div>

<style>
    
    @media only screen and (min-width:0px){
        .card {
            width: 90%;
            margin-left: 5%
        }
        .card-content {
            padding-top: 3%;
            padding-bottom: 3%;
        }
        .card-info p {
            font-size: 14px
        }
        .color-circle {
            width: 30px;
            height: 30px;
            margin: 5px;
            border-radius: 50%;
        }
        .color-label {
            font-size: 10px !important;
            color: rgb(111, 111, 111);
            text-align: center
        }
        .card-title {
            font-family: oskar;
            font-size: 26px !important;
            color: rgb(0, 0, 0);
            margin-bottom: 0 !important;
        }
        .card-price {
            font-family: oskar;
            font-size: 22px;
            color: rgb(44, 150, 44)
        }
        .carousel {
            height: 300px;
            -khtml-transition: height 0.5s ease;
            -moz-transition: height 0.5s ease;
            -ms-transition: height 0.5s ease;
            -o-transition: height 0.5s ease;
            -webkit-transition: height 0.5s ease;
            transition: height 0.5s ease;
        }
        .carousel-item {
            margin-top: 0px !important;
        }
        .carousel-image-item {
            display: flex;
        }
        #merchandise-container {
            margin-top: 0;
            padding-top: 10px;
            background-color: rgba(255, 255, 255, 0.954);
        }
        .merch-row1 {
            display: flex;
            flex-wrap: wrap;
            padding-top: 10px
        }
        .indicator-item {
            background-color: rgb(122, 235, 135) !important
        }
        .indicator-item.active {
            background-color: rgb(229, 244, 231) !important
        }
        svg {
            stroke: transparent !important;
        }
        label {
            font-family: poppins;
        }
        .dropdown-content li>span {
            color: black
        }
        .select-wrapper input.select-dropdown {
            font-family: poppins;
            font-size: 14px;
            letter-spacing: 1px;
            color: rgb(103, 103, 103)
        }
        .size-field {
            width: 50%;
            margin: 0
        }
        .size-row {
            margin-bottom: 0; 
            display: flex; 
            justify-content: center;
        }
        .page-title {
            font-family: oskar; 
            font-size: 42px;
            text-align: center;
            color: rgb(176, 39, 39)
        }
        .donation-subtitle {
            text-align: left;
            padding-left: 2%;
            padding-right: 3%;
            border-left: dotted 2px grey;
            margin-left: 5%;
            font-family: poppins;
            font-weight: 300;
            font-size: 14px;
            letter-spacing: 1px;
            line-height: 18px
        }
        .donation-subtitle b {
            font-weight: 500 !important
        }
        
        .lb-outerContainer {
            width: 95% !important;
            height: 95vw !important;
        }
        .lb-image {
            width: 100% !important;
            height: 100% !important
        }
        .color-radio::before, .color-radio::after {
            width: 30px !important;
            height: 30px !important;
            margin: 0 !important;
            border: none !important;
            -webkit-box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.2); 
            box-shadow: 0px 1px 3px 1px rgba(0,0,0,0.2);
        }
        [type="radio"]:checked+span:after {
            background: transparent !important;
            -webkit-box-shadow: 0px 0px 0px 2px rgb(2, 215, 34); 
            box-shadow: 0px 0px 0px 3px rgb(18, 171, 41);
        }
    }
    @media only screen and (min-width:500px){

        .carousel-item {
            margin-top: 0px !important
        }
        .card-column {
            flex-grow: 1;
        }
        .size-field {
            width: 30%;
            margin: 0
        }
        .page-title {
            font-size: 48px;
        }
        .donation-subtitle {
            
            font-family: poppins;
            font-weight: 300;
            font-size: 18px;
            letter-spacing: 1px;
            line-height: 22px
        }
    }
    @media only screen and (min-width:601px){
        .card {
            width: 100%;
            margin-left: 0;
        }
        .card-content {
            padding-left: 0 !important;
            padding-right: 0 !important
        }
        .card-image img {
            padding:0;
        }
        .card-column {
            display: block
        }
        .merch-row1 {
            padding-left: 0%;
            padding-right: 0%;
            padding-bottom: 0px;
            margin-bottom: 0;
            display: block
        }
        .size-field {
            width: 50%;
            margin: 0
        }
    }
    @media only screen and (min-width:900px){
        .size-field {
            width: 40%;
            margin: 0
        }
        .lb-outerContainer {
            width: 70% !important;
            height: 70vw !important;
        }
    }
    @media only screen and (min-width:992px){
        .size-field {
            width: 40%;
            margin: 0
        }
        .merch-row1 {
            padding-left: 5%;
            padding-right: 5%;
        }
    }
    @media only screen and (min-width:1201px){
        .size-field {
            width: 30%;
            margin: 0
        }
        .lb-outerContainer {
            width: 50% !important;
            height: 50vw !important;
        }
    }
    @media only screen and (min-width:1226px){
        #merchandise-container {
           padding-top: 60px !important
        }
    }
</style>
<script>
    $(document).ready(function(){
        
        $('.carousel.carousel-slider').carousel({
            fullWidth: true,
            indicators: true,
        });
        $('.materialboxed').materialbox();
        lightbox.option({
            'maxWidth': '300px',
            'maxHeight': '300px',
            'wrapAround': true
        });
        
       
    });
    $( window ).on( "load", function() {
        var finalHeight = $('.carousel-image-item').first().innerHeight()
        $('.carousel').css('height', finalHeight)
    });
    var productForm = $(".ajax-product-form")

    productForm.submit(function(event){
        event.preventDefault();
        var thisForm = $(this)
        var size = $(thisForm).find("option:selected").val()
        var color = $(thisForm).find("input[class=select-color]:checked").val()
        var type = $(thisForm).children('.product-id-hidden').val()
        
        var formData = {
            'id': type,
            'size': size,
            'color': color,
        };
        $.ajax({
            url: '{% url "merchandise:add-to-cart" %}',
            method: 'GET',
            data: formData,
            success: function(data){
                Swal.fire(
                    'Added to Cart!',
                    'Continue Shopping',
                    'success'
                );
                
                
            },
            error: function(errorData){
                Swal.fire(
                    'An Error Occured',
                    errorData,
                    'error'
                );
            }
        })
    });
    
</script>
{% endblock %}