accounts/passwords/urls.py
# accounts.passwords.urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns  = [
url(r'^password-change/$',
        auth_views.PasswordChangeView.as_view(template_name='accounts/snippets/passwords/change-password.html'),
        name='password_change'),
url(r'^password/change/done/$',
        auth_views.PasswordChangeDoneView.as_view(template_name='accounts/snippets/passwords/change-password-success.html'),
        name='password_change_done'),
url(r'^password/reset/$',
        auth_views.PasswordResetView.as_view(template_name='accounts/snippets/passwords/change-password.html'),
        name='password_reset'),
url(r'^password/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
url(r'^password/reset/\
        (?P<uidb64>[0-9A-Za-z_\-]+)/\
        (?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),

url(r'^password/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),
]

accounts/urls.py
from django.urls import path
from .views import RegisterView, AccountHomeView, JoinTeam

urlpatterns = [
    path('my-account/', AccountHomeView, name='home'),
    path('join-team/', JoinTeam, name='jointeam')
]

etv/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

from django.urls import path, include
from django.views.generic import RedirectView
from accounts.admin import admin_site

from .views import *
from accounts.views import LoginView, RegisterView, GuestRegisterView
from content.views import efbf, contact, mailchimp_signup

from policy.views import obb_flyer
from vbp.models import *
from ven.views import *

from merchandise.views import ProductList

Alabama = vbp_al.objects.filter(approved=False).count()
Alaska = vbp_ak.objects.filter(approved=False).count()
Arizona = vbp_az.objects.filter(approved=False).count()
Arkansas = vbp_ar.objects.filter(approved=False).count()
California = vbp_ca.objects.filter(approved=False).count()
Colorado = vbp_co.objects.filter(approved=False).count()
Connecticut = vbp_ct.objects.filter(approved=False).count()
Delaware = vbp_de.objects.filter(approved=False).count()
DistrictofColumbia = vbp_dc.objects.filter(approved=False).count()
Florida = vbp_fl.objects.filter(approved=False).count()
Georgia = vbp_ga.objects.filter(approved=False).count()
Hawaii = vbp_hi.objects.filter(approved=False).count()
Idaho = vbp_id.objects.filter(approved=False).count()
Illinois = vbp_il.objects.filter(approved=False).count()
Indiana = vbp_in.objects.filter(approved=False).count()
Iowa = vbp_ia.objects.filter(approved=False).count()
Kansas = vbp_ks.objects.filter(approved=False).count()
Kentucky = vbp_ky.objects.filter(approved=False).count()
Louisiana = vbp_la.objects.filter(approved=False).count()
Maine = vbp_me.objects.filter(approved=False).count()
Maryland = vbp_md.objects.filter(approved=False).count()
Massachusetts = vbp_ma.objects.filter(approved=False).count()
Michigan = vbp_mi.objects.filter(approved=False).count()
Minnesota = vbp_mn.objects.filter(approved=False).count()
Mississippi = vbp_ms.objects.filter(approved=False).count()
Missouri = vbp_mo.objects.filter(approved=False).count()
Montana = vbp_mt.objects.filter(approved=False).count()
Nebraska = vbp_ne.objects.filter(approved=False).count()
Nevada = vbp_nv.objects.filter(approved=False).count()
NewHampshire = vbp_nh.objects.filter(approved=False).count()
NewJersey = vbp_nj.objects.filter(approved=False).count()
NewMexico = vbp_nm.objects.filter(approved=False).count()
NewYork = vbp_ny.objects.filter(approved=False).count()
NorthCarolina = vbp_nc.objects.filter(approved=False).count()
NorthDakota = vbp_nd.objects.filter(approved=False).count()
Ohio = vbp_oh.objects.filter(approved=False).count()
Oklahoma = vbp_ok.objects.filter(approved=False).count()
Oregon = vbp_or.objects.filter(approved=False).count()
Pennsylvania = vbp_pa.objects.filter(approved=False).count()
RhodeIsland = vbp_ri.objects.filter(approved=False).count()
SouthCarolina = vbp_sc.objects.filter(approved=False).count()
SouthDakota = vbp_sd.objects.filter(approved=False).count()
Tennessee = vbp_tn.objects.filter(approved=False).count()
Texas = vbp_tx.objects.filter(approved=False).count()
Utah = vbp_ut.objects.filter(approved=False).count()
Vermont = vbp_vt.objects.filter(approved=False).count()
Virginia = vbp_va.objects.filter(approved=False).count()
Washington = vbp_wa.objects.filter(approved=False).count()
WestVirginia = vbp_wv.objects.filter(approved=False).count()
Wisconsin = vbp_wi.objects.filter(approved=False).count()
Wyoming = vbp_wy.objects.filter(approved=False).count()

urlpatterns = [
    path('contact/', contact, name='contact' ),
    path('myadmin/etvadmin209423/', admin_site.urls, {'extra_context': {
        'AL': Alabama,
        'AK': Alaska,
        'AZ': Arizona,
        'AR': Arkansas,
        'CA': California,
        'CO': Colorado,
        'CT': Connecticut,
        'DE': Delaware,
        'DC': DistrictofColumbia,
        'FL': Florida,
        'GA': Georgia,
        'HI': Hawaii,
        'ID': Idaho,
        'IL': Illinois,
        'IN': Indiana,
        'IA': Iowa,
        'KS': Kansas,
        'KY': Kentucky,
        'LA': Louisiana,
        'ME': Maine,
        'MD': Maryland,
        'MA': Massachusetts,
        'MI': Michigan,
        'MN': Minnesota,
        'MS': Mississippi,
        'MO': Missouri,
        'MT': Montana,
        'NE': Nebraska,
        'NV': Nevada,
        'NH': NewHampshire,
        'NJ': NewJersey,
        'NM': NewMexico,
        'NY': NewYork,
        'NC': NorthCarolina,
        'ND': NorthDakota,
        'OH': Ohio,
        'OK': Oklahoma,
        'OR': Oregon,
        'PA': Pennsylvania,
        'RI': RhodeIsland,
        'SC': SouthCarolina,
        'SD': SouthDakota,
        'TN': Tennessee,
        'TX': Texas,
        'UT': Utah,
        'VT': Vermont,
        'VA': Virginia,
        'WA': Washington,
        'WV': WestVirginia,
        'WI': Wisconsin,
        'WY': Wyoming,
    }}, name='myadmin', ),
    path('', home_page, name='home'),
    path('privacy-policy', privacy, name="privacy"),
    path('terms-and-conditions', terms, name="terms"),
    path('about/', about_page, name='about'),
    path('accounts/', RedirectView.as_view(url='/account')),
    path('account/', include(("accounts.urls", "accounts"), namespace='account')),
    path('black-friday-challenge/', include(("bfchallenge.urls", "bfchallenge"), namespace='bfchallenge')),
    path('billing/', include(("billing.urls", "billing"), namespace='billing')),
    path('cart/', include(("carts.urls", "carts"), namespace='carts')),
    path('dashboard/', include(("dashboard.urls", "dashboard"), namespace='dashboard')),
    path('donation/', include(("donations.urls", "donations"), namespace='donation')),
    path('economic-prosperity-and-employment/', include(("prosperity.urls", "prosperity"), namespace='prosperity')),
    path('events/', include(("events.urls", "events"), namespace='events')),
    path('news/', news, name='news'),
    path('news-and-events/', news, name='news'),
    path('sitemap.xml/', sitemap),
    path('robots.txt/', robots),
    path('shop/', ProductList, name='shop'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page=settings.LOUGOUT_REDIRECT_URL), name='logout'),
    path('make-every-friday-black-friday/', efbf, name='efbf'),
    path('mailchimp-signup/', mailchimp_signup, name='mailchimp-signup'),
    path('merchandise/', include(("merchandise.urls", "merchandise"), namespace='merchandise')),
    path('obb-<state>/', obb_flyer),
    path('register/', RegisterView.as_view(), name='register'),
    path('register/guest', GuestRegisterView.as_view(), name='guest_register'),
    path('scraper/', include(("scraper.urls", "scaper"), namespace="scraper")),
    path('settings/', RedirectView.as_view(url='/account')),
    path('strategic-pillars/', strategic_pillars, name='pillars'),
    path('village-black-pages/', include(("vbp.urls", "vbp"), namespace='vbp')),
    path('', include('social_django.urls', namespace='social')),
    path('health-and-wellness/', include(("health.urls", "health"), namespace='health')),
    path('policy-and-power/', include(("policy.urls", "policy"), namespace='policy')),
    path('education/', include(("education.urls", "education"), namespace='education')),
    path('walkathon/', include(("walkathon.urls", "walkathon"), namespace="walkathon")),
    path('power-walk-2023/', include(("walkathon.urls", "walkathon"), namespace="power-walk")),
    path('power-walk-2024/', include(("walkathon.urls", "walkathon"), namespace="power-walk-24")),
    path('village-empowerment-network/', include(("ven.urls", "ven"), namespace='ven')),
    path('village-empowerment-network-nomination/', venForm, name='ven-nomination'),
    path('tinymce/', include('tinymce.urls')),
    
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from datetime import timedelta
import random
from django.contrib.auth.models import Group
from django.db import models
from django.db.models import Q
from django.db import models
from django.db import IntegrityError
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from django.conf import settings
from django.db.models.signals import pre_save, post_save
from django.core.mail import send_mail
from django.template.loader import get_template
from django.urls import reverse
from django.utils import timezone
from django.core.mail import send_mail
from mailchimp_marketing import Client
from mailchimp_marketing.api_client import ApiClientError

mailchimp = Client()
mailchimp.set_config({
    "api_key": settings.MAILCHIMP_API_KEY,
    "server": "us7"
})

CHALLENGE_CHOICES = (
    ('bingo', 'Power Bingo'),
    ('rss', 'Ready, Set, Shop!')
)
class MyUserManager(BaseUserManager):
    def create_user(self, email, username=None, is_active=True, staff=False, admin=False, password=None):
        if not email:
            raise ValueError('An email address is required')
        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )
        user.set_password(password)
        user.staff = staff
        user.is_active = user.active
        user.admin = admin
        user.save(using=self._db)
        return user

    def create_staffuser(self, password, email):
        user = self.create_user(
            email,
            password=password,
        )
        user.staff = True
        user.admin = True
        user.save(using=self._db)
        
        return user

    def create_superuser(self, username, password, email):
        user = self.create_user(
            email,
            password=password,
            username=username
        )
        user.staff = True
        user.admin = True
        user.save(using=self._db)
        return user

class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    username = models.CharField(max_length=100, unique=True, blank=True, null=True)
    full_name = models.CharField(max_length=225, blank=True, null=True, unique=False)
    first_name = models.CharField(max_length=225, blank=True, null=True, unique=False)
    last_name = models.CharField(max_length=225, blank=True, null=True, unique=False)
    active = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)
    team = models.ForeignKey('Team', on_delete=models.SET_NULL, blank=True, null=True)
    is_donor = models.BooleanField(default=False, blank=True, null=True)
    rss_sponsor = models.BooleanField(default=False, blank=True, null=True)
    bingo_sponsor = models.BooleanField(default=False, blank=True, null=True)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def get_full_name(self):
        return self.username

    def get_short_name(self):
        return self.username

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_active(self):
        return self.active

    @property
    def is_donor(self):
        return self.is_donor

    @property
    def is_rss_sponsor(self):
        return self.rss_sponsor
    
    @property
    def is_bingo_sponsor(self):
        return self.bingo_sponsor

class GuestEmail(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

class Team(models.Model):
    team_name = models.CharField(max_length=200, unique=True)
    paid = models.BooleanField(default=False)
    challenge_access = models.CharField(choices=CHALLENGE_CHOICES, blank=True, max_length=100)
    active = models.BooleanField(default=True)
    
    def __str__(self):
        return self.team_name

class Participant(models.Model):
    email = models.EmailField(max_length=255)
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    team = models.ForeignKey(Team, blank=True, null=True, on_delete=models.CASCADE)
    def __str__(self):
        return self.email

accounts/views.py
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import HttpResponse
from django.views.generic import CreateView, FormView, DetailView, View, UpdateView, ListView
from django.views.generic.edit import FormMixin
from django.urls import reverse
from django.utils.safestring import mark_safe

from billing.models import BillingProfile
from .forms import LoginForm, RegisterForm, GuestForm, UserTeamForm
from bfchallenge.models import nomination
from accounts.models import Team
from donors.models import Donor
from orders.models import Order

from etv.mixins import NextUrlMixin, RequestFormAttachMixin
from .models import GuestEmail
from .signals import user_logged_in

import datetime
from django.shortcuts import render, redirect
import sweetify

User = get_user_model()

def AccountHomeView(request):
    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    nomination_qs = nomination.objects.filter(user=request.user).count()
    donor_obj = Donor.objects.filter(user=request.user).first()
    total = 0
    recent = datetime.datetime.now() + datetime.timedelta(days=-7)
    recent_qs = None
    if donor_obj is not None:
        donation_qs = donor_obj.donations.all()
        for x in donation_qs:
            total += x.amount
        recent_qs = donation_qs.filter(updated__gte=recent, status="complete")
    donation_qs = None
    order_qs = Order.objects.filter(billing_profile=billing_profile).filter(status='submitted_for_settlement')
    context = {
        'nomination_qs': nomination_qs,
        'donations': donation_qs,
        'recent': recent,
        'recent_qs': recent_qs,
        'total': total,
        'orders': order_qs,
        'bp': billing_profile
    }
    return render(request, 'accounts/home.html', context)

class GuestRegisterView(NextUrlMixin, RequestFormAttachMixin, CreateView):
    form_class = GuestForm
    default_next = '/register/'

    def get_success_url(self):
        return self.get_next_url()

    def form_invalid(self, form):
        return redirect(self.default_next)

class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'
    success_url = '/login/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        teams = Team.objects.all()
        context["team_list"] = teams
        return context

def JoinTeam(request):
    context = {
        'title': 'ETV | Join Team'
    }
    if request.method == 'POST':
        form = UserTeamForm(request.POST)
        form_team = form.data['team']
        obj, created = Team.objects.get_or_create(
            team_name=form_team
        )
        obj.save()
        user = request.user
        user.team = obj
        user.save()
        sweetify.success(request, title='Thank you!', icon='success', text="You've successfully joined a team!", button='OK', timer=4000)
        return redirect('/account/my-account/')
    else:
        form = UserTeamForm(instance=request.user)
        context={
            'form': UserTeamForm(),
            'teams': Team.objects.all()
        }
    return render(request, 'accounts/join-team.html', context)

class LoginView(NextUrlMixin, RequestFormAttachMixin, FormView):
    form_class = LoginForm
    success_url = '/'
    template_name = 'accounts/sociallogin.html'
    default_next = '/'
    register_form = RegisterForm

    def form_valid(self, form):
            return redirect('/')

accounts/templates/accounts/adminlogin.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div id="page">
  <div class="row center-align" style="margin-top:0px">
    <div class="col s8 m8 l6 login-card" style="background-color:#fdfdfde5;padding-top:30px; padding-bottom:40px">
        <h6 id="login-title">Login</h6>
        <p id="new-to-village">New to The Village? <a href="{% url 'register' %}" >Register for a free account now!</p></a>
        
      <form class="form center" method='POST' style="padding-left: 10%; padding-right:10%; width: 70%; margin-left:15%">
        
        {% csrf_token %}
         {{ form }}
        <button type="submit" class='btn login-btn' style="margin-top:24; padding:22px; line-height:0px; margin-bottom:15px">Login</button>
      
      </form>
      
    </div>
  </div>
</div>

<style>
  #page {
    background-image: url("{% static 'img/login-collage.svg' %}");
    background-size: 50%;
    background-repeat: repeat;
  }
  #id_username {
    letter-spacing: 1px;
    width:100%;
    font-family: 'Poppins';
    font-weight:200;
  }
  #id_password {
    font-weight: 200;
    letter-spacing: 1px;
    font-family: 'Poppins';

  }
</style>
{% endblock %}


accounts/templates/accounts/detail-update-view.html
{% extends "base.html" %}

{% block content %}
{% url 'account:home' as account_home_url %}
<div class='ui grid'>
  <div class="ui container">
  <div class="ui breadcrumb">
    <a class="section" href="{{ account_home_url }}">Account Home</a>
    <i class="right chevron icon divider"></i>
    <div class="active section">Update Username</div>
  </div>
  </div>
  <div class='ui centered row'>
  {% if title %}<h1 style='font-family:"Quicksand", sans serif; font-weight:400'>{{ title }}</h1>{% endif %}
  </div>
</div>
<div class='ui center aligned text container'>
    <div class='ui row'>
        <form method='post' action='{% if action_url %}{{ action_url }}{% endif %}' class="ui form">{% csrf_token %}
          {% if next_url %}
          <input type='hidden' name='next' value='{{ next_url }}' />
          {% endif %}
           {{ form.as_p }}
        <label for='email'>Email Address:</label>
        <input type='text' value='{{ request.user.email }}' class='ui disabled input' disabled='disabled'/><span class='help-text'>Changes to email address are not yet supported, but we're working on it!</span><br/>
        <br/><a href='{% url "password_change" %}'>Click Here to Change Password</a>
        <br/><button type="submit" class='ui button' style='margin-top:20'>Save</button>
        </form>
      </div>

</div>

{% endblock %}

accounts/templates/accounts/home.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}

<div id="page">
<div class="row" style=" padding-top:60px; padding-bottom: 60px;padding-left: 5%; padding-right: 5%; background-color: rgba(250, 250, 250, 0.742)">
<h5 class="" style="text-transform: capitalize;">Welcome back{% if user.first_name %}, {{ user.first_name }}{% endif %}!</h5>
<div class="row">
  <div class="col s12 m10 l8">
    <div class="card " style="margin-bottom:10">
      <div class="card-content">
        <span class="card-title">My Account</span>
        <ul class="account-list">
          {% if user.is_staff %}
          <li><a href="/myadmin/etvadmin209423/">Take Me To ETV Admin</a></li>
          {% endif %}
          <li><b>Username:</b> {{ user.username }}</li>
          <li><b>Email Address:</b> {{ user.email }}</li>
          <li><b>Team:</b>
            {% if user.team %}
            {{ user.team }}
            {% else %}
            <a href="{{ join_url }}">Join a Team!</a>
            {% endif %}
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col s12 l4">
    <div class="card" style="margin-bottom:10">
      <div class="card-content">
        <span class="card-title">Black Friday Challenge™ Dashboard</span>
        <ul class="bf-challenge-list">
          <li>Nomination Challenge</li>
            <p></p><a href="{{ nomination_url }}">Nominate a Black-owned business today!</a></p>
          <br>
          <li>Power Bingo</li>
            {% if user.is_bingo_sponsor %}
            <a href="{{ bingo_url }}">Click here to view your Power Bingo board</a>
            {% else %}
            <a href="{{ contact_url }}">Contact Empower The Village to sponsor a Power Bingo game today!</a>
            {% endif %}
          <br>
          <br>
          <li>Ready, Set, Shop!</li>
            {% if user.team %}
            <p><a>{{ user.team }}</a></p>
            {% else %}
            <a href="{{ join_url }}">Join a Team!</a>
            {% endif %}
          </li>
          <br>
          <li>Spread The Love</li>
          <p>Spread the word about Black-owned businesses! <a href="{{ stl_url }}">Drop us a link to your Instagram post!</a></p>
        </ul>
      </div>
    </div>
  </div>
  <div class="col s12 l4">
    <div class="card" style="margin-bottom:10">
      <div class="card-content">
        <span class="card-title">Order Dashboard</span>
        <ul class="bf-challenge-list">
          <li>My Orders</li>
            <ul >
              <div class="divider" style="margin-top: 10px; margin-bottom: 10px"></div>
              {% for x in orders %}
              <li>
                <p><b>Order Id: </b><b style="font-weight: 300">{{ x }}</b></p>
                <p><b>Tracking: </b><a target="_blank" href="" style="font-weight: 300"></a></p>
                <p><b>Items:</b></p>
                <p style="font-weight: 300">{% for item in x.items.all %}{{ item.product }}{% endfor %}</p>
                <p><b>Total:</b> ${{ x.total }}</p>
              </li>
              <div class="divider" style="margin-top: 10px; margin-bottom: 10px"></div>
              {% endfor %}
            </ul>
            <br>
          
          <li><a href="{{ merchandise_url }}">Shop Now!</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="col s12 l4">
    <div class="card" style="margin-bottom:10">
      <div class="card-content">
        <span class="card-title">Donation Dashboard</span>
        <ul class="bf-challenge-list">
          <li>My Recent Donations</li>
            <ul>
              {% for donation in recent_qs %}
              <p>{{ donation.updated }} - <b style="color: green">${{ donation.amount }}</b></p>
              {% endfor %}
            </ul>
            <br>
          <li>Total Donated</li>
            <p>${{ total|intcomma }}</p>
          <li><a href="{{ donate_url }}">Donate Now!</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>





</div>
</div>
<style>
#page {
    background-image: url("{% static 'img/login-collage.svg' %}");
    background-size: 50%;
    background-repeat: repeat;
    height: 100%
  }
.bf-challenge-list li {
  font-size:18px;
  font-weight:500;
}
.account-list {
  font-size: 18px
}
.card {
}
</style>
{% endblock %}

accounts/templates/accounts/join-team.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div id="page">
    <div class="row center-align" style="margin-top:0px">
      <div class="col s8 m8 l6 login-card" style="background-color:#fdfdfde5;padding-top:30px; padding-bottom:40px">
          <h6 id="login-title">Join A Team</h6>
          <p id="new-to-village">Join a team today to get involved in ETV's economic prosperity initiatives!
          
        <form class="form center" method='POST' style="padding-left: 10%; padding-right:10%; width: 70%; margin-left:15%">
          
          {% csrf_token %}
          {% for field in form %}
          <div class="input-field">
           {{ field }}
           <label>{{ field.label }}</label>
          </div>
          {% endfor %}
          <button type="submit" class='btn login-btn' style="margin-top:24; padding:22px; line-height:0px; margin-bottom:15px">Join Team</button>
          
        </form>
        
      </div>
    </div>
  </div>
  
  <style>
    #page {
      background-image: url("https://empowerthevillage.s3.amazonaws.com/static/img/login-collage.svg");
      background-size: 50%;
      background-repeat: repeat;
    }
    #id_email {
      padding-left:15px;
      letter-spacing: 1.5px;
      width:100%
    }
    #id_password {
      padding-left: 15px;
      font-weight: 200;
    }
  </style>
  {% endblock %}

accounts/templates/accounts/sociallogin.html
{% extends 'base.html' %}
{% load static %}
{% block title %}ETV | Login{% endblock %}
{% block canonical %}https://www.empowerthevillage.org/login/{% endblock %}
{% block seo_description %}Login to manage your account and participate in ETV's fun Black Friday Challenges!{% endblock %}

{% block content %}
<div id="page">
  <div class="row center-align" style="margin-top:0px">
    <div class="col s12 m8 l6 login-card center-align z-depth-2" style="background-color:#fdfdfdf1;padding-top:3%; padding-bottom:3%">
        <h6 id="login-title">Login</h6>
        <p id="new-to-village">New to The Village? <a href="{% url 'register' %}" >Register for a free account now!</p></a>
        
      <form class="form center col s11 m8 offset-m2" method='POST'>
        
        {% csrf_token %}
         {{ form }}
        <button type="submit" class='btn login-btn' style="margin-top:24; padding:22px; line-height:0px; margin-bottom:15px">Login</button>
      </form>
      
    </div>
  </div>
</div>

<style>
  #page {
    background-image: url("https://pub-91c8b4fa01b34d9cb1fda46285f07f62.r2.dev/vbp-collage.webp");
    background-size: 80%;
    background-repeat: repeat;
  }
  #id_email {
    padding-left:15px;
    letter-spacing: 1.5px;
    width:100%
  }
  #id_password {
    padding-left: 15px;
    font-weight: 200;
  }
</style>
{% endblock %}
